### PR TITLE
Use the configured remote when pushing tags

### LINKED ISSUE #39: Release command ends up silently creating wrong tag when tag was pushed to a wrong remote
Release command can push tag to a wrong remote and then proceed to create a release.
Since in that case tag will not be present in the release repository, github will silently create annotated tag.

Since release target is specified in `<org>/<repo>` format, it was a surprise that it used default `origin` remote.
Github tags page shows `Verified` signature status of the commit pointed by the tag with proper key id so it is very hard to notice something went wrong.

Suggested solution:
- Convenience check if remote url matches default github/gitlab pattern for git or https urls. If it is, verify it matches specified org and repository. Fail early.
- Proper: Use api to verify tag ref is present in release repository before api call to create a release is made. Bonus points for checks whether `object` obtained from tag ref is of type `tag` (as opposed to annotated tag, which will have object of type `commit` i believe)

Usage that led to the issue occurence:
I am using `hub`, a cli wrapper around git for interacting with github.
In the github/hub flow `origin` points to a fork and `upstream` to original repository:
```bash
[zend-tag (master)]$ git remote -v
origin	git@github.com:Xerkus/zend-tag.git (fetch)
origin	git@github.com:Xerkus/zend-tag.git (push)
upstream	git@github.com:zendframework/zend-tag.git (fetch)
upstream	git@github.com:zendframework/zend-tag.git (push)
```
Terminal history leading to the problem:
```bash
[zend-tag (master +)]$ git commit -m "2.7.1 readiness"
[master a9f92a0] 2.7.1 readiness
 1 file changed, 1 insertion(+), 1 deletion(-)
[zend-tag (master)]$ keep-a-changelog tag -a release-2.7.1 2.7.1
Created tag "2.7.1" for package "zend-tag" using the following notes:
Added
-----

- [#22](https://github.com/zendframework/zend-tag/pull/22) adds support for PHP 7.3.

Changed
-------

- Nothing.

Deprecated
----------

- Nothing.

Removed
-------

- Nothing.

Fixed
-----

- Nothing.
[zend-tag (master)]$ keep-a-changelog release zendframework/zend-tag 2.7.1 -a release-2.7.1
Preparing changelog for release
Pushing tag 2.7.1 to origin
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 8 threads
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 3.29 KiB | 3.29 MiB/s, done.
Total 11 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
To github.com:Xerkus/zend-tag.git
 * [new tag]         release-2.7.1 -> release-2.7.1
Creating release "zend-tag 2.7.1"        <<<<-------- github silently creates annotated tag
Created https://github.com/zendframework/zend-tag/releases/tag/release-2.7.1
```

### PR DESCRIPTION
**Pull request by weierophinney**
This patch modifies the `release` command such that it now looks up which remote to push a tag to based on:

- remotes configured for PUSH operations
- remote URLs matching the provider domain name
- remote URLs matching the package name in the path

The name of the first remote to satisfy all three criteria is returned and used for pushing tags. Otherwise, the command indicates an error occurred, provides information for debugging why, and exits with a failure status.

Additionally, this patch provides additional logic in the `GitHub` provider to verify the tag before attempting to create a release. It looks for:

- A git reference matching the given tag.
- Tag details matching the sha reference for the tag.
- Tag verification in the tag details.

If any of these three fails, release creation will raise an exception, causing the command to abort.

Between these two changes, tag pushes and release creation should only ever occur on the canonical repository, for signed tags.

Fixes #39

### CODE REVIEW

**Comment by weierophinney** [comment]
@Xerkus This addresses the first bit of your suggested fix: failing early when we cannot find an appropriate remote.

I tried a few different combinations locally, and in each case, it was correctly finding the remote to which to push; when it could not find a remote configured for push operations, or matching both the provider domain name and the package name in the path, it was bailing early, and suggesting I double-check my git configuration.

Since the tag push operation causes the command to bail on failure, I don't see a need to check for the tag on completion, so long as the command is using the correct remote.

The one potential problem still lingering is that if multiple remotes match, this functionality will return the first to match, which may still not be correct. One thing I _could_ also do is check to see if _multiple_ remotes match, and ask the user to select, which would resolve that issue. Should I make those changes as well before merging this?

**Comment by Xerkus** [comment]
> The one potential problem still lingering is that if multiple remotes match, this functionality will return the first to match, which may still not be correct. One thing I _could_ also do is check to see if _multiple_ remotes match, and ask the user to select, which would resolve that issue. Should I make those changes as well before merging this?

My overcautious side calls for abort and explicit flag. But in practice I do not think it will matter. At worst it will fail on push and user will need to explicitly provide remote name.
One special rule for this case is to make remotes `origin` and `upstream` be inspected first.

**Comment by Xerkus** [comment]
As for safeguard for creating release on github, github provider would need to be updated with one extra api call and assert for the returned value:
https://github.com/phly/keep-a-changelog/blob/8585813060576fc939772a7b1e37b8b6a7ff438d/src/Provider/GitHub.php#L19-L42
Something like this:
```php
$client->authenticate($token, GitHubClient::AUTH_HTTP_TOKEN); 
$tagRef = $client->get('gitData')->references()->show('tags/' . rawurlencode($tagName));
// didn't check for 404 condition. How library handles it? Exceptions?
$tagType = $tagRef['object']['type'] ?? null;
if ($tagType === 'tag') {
    // proper signed tag <-- those we create and push
} elseif ($tagType === 'commit') {
    // unsigned, annotated tag object: git tag -a
    // we do not allow those in Zend Framework repos
    // Also this type is silently created by github if tag does not exist in the repository for release.
    // UI does not show them as unsigned tags, showing verified seal of the commit they point to.
} else {
    // something went wrong
}
// continue with create release api call
```

**Comment by weierophinney** [comment]
I've done a little experimentation, and what I've found is that if a matching `refs/tags/{tagName}` reference is found, the type is **always** `tag`, even for those that were not signed; there is literally nothing differentiating them in the API result. When a particular tag reference _is not found_, the client raises an exception.

What we **can** do, however, is use the data returned by fetching the reference to fetch the tag data:

```php
$tagData = $client->api('gitData')->tags()->show($org, $repo, $tagRef['object']['sha']);
```

The data returned from that includes a "verification" object, with a "verified" subkey that indicates if the tag has an associated signature. That value is a boolean, with `true` indicating a signature was matched.

I'll make those changes shortly.

**Comment by Xerkus** [comment]
Actually I was wrong, annotated tag does create a tag object, it is not signed.
`tag -a`:
```json
{
  "ref": "refs/tags/test",
  "node_id": "MDM6UmVmMTg1MjMyMjE1OnRlc3Q=",
  "url": "https://api.github.com/repos/Xerkus/zend-authentication/git/refs/tags/test",
  "object": {
    "sha": "8b21a7924310a11d7623e7b863453f3e160f8d78",
    "type": "tag",
    "url": "https://api.github.com/repos/Xerkus/zend-authentication/git/tags/8b21a7924310a11d7623e7b863453f3e160f8d78"
  }
}
```
`tag -s`:
```json
{
  "ref": "refs/tags/test-s",
  "node_id": "MDM6UmVmMTg1MjMyMjE1OnRlc3Qtcw==",
  "url": "https://api.github.com/repos/Xerkus/zend-authentication/git/refs/tags/test-s",
  "object": {
    "sha": "5a5885eda25638e85893df9748fbedab5d622f0e",
    "type": "tag",
    "url": "https://api.github.com/repos/Xerkus/zend-authentication/git/tags/5a5885eda25638e85893df9748fbedab5d622f0e"
  }
}
```
non-annotated unsigned `tag`:
```json
{
  "ref": "refs/tags/test-r",
  "node_id": "MDM6UmVmMTg1MjMyMjE1OnRlc3Qtcg==",
  "url": "https://api.github.com/repos/Xerkus/zend-authentication/git/refs/tags/test-r",
  "object": {
    "sha": "cbfec9c0270b8c3139c16d00ef93fc800d0dd190",
    "type": "commit",
    "url": "https://api.github.com/repos/Xerkus/zend-authentication/git/commits/cbfec9c0270b8c3139c16d00ef93fc800d0dd190"
  }
}
```
For the purposes of the provider assertion for release command it would be enough to ensure the presence of the tag in the target.

Existing wrong tag in the target will cause tag push operation to fail, so from practical standpoint correctness of the tag is covered by ensuring proper remote is used.

**Comment by weierophinney** [comment]
@Xerkus Commit f23e900 provides the logic to verify the tag was (a) pushed, and (b) signed. I think with those in place, your issues are finally addressed!

File: src/Provider/GitLab.php [hunk 1]
```diff
@@ -62,4 +63,14 @@ public function generatePullRequestLink(string $package, int $pr) : string
...
     }
+
+    public function getName() : string
+    {
+        return 'GitLab';
+    }
+
+    public function getDomainName() : string
+    {
+        return 'gitlab.com';
```
Comment (Xerkus) [inline src/Provider/GitLab.php]: May be make it configurable rather than hardcoded, to allow for self-hosted gitlab?

File: src/ReleaseCommand.php [hunk 2]
```diff
@@ -131,7 +132,28 @@ protected function execute(InputInterface $input, OutputInterface $output) : int
...
+        if (! $remotes) {
+            $output->writeln('<error>Cannot determine remote to which to push tag!</error>');
+            $output->writeln(
+                'The command "git remote -v" had a non-zero exit status; verify the command works, and try again.'
+            );
+            return 1;
+        }
+
+        $provider = $this->getProvider($config);
+        $remote   = $input->getOption('remote') ?: $this->lookupRemote(
```
Comment (Xerkus) [inline src/ReleaseCommand.php]: Possible improvement is to check if remote url matches expectation and to show notice message in the output in case it did not.

File: src/Provider/GitLab.php (hunk 1 above)
Comment (weierophinney) [reply src/Provider/GitLab.php]: Users can create a custom provider in such scenarios.

Comment (weierophinney) [reply src/Provider/GitLab.php]: Hm... they can't, actually. The `GetConfigValuesTrait` hardcodes that information. The configuration would need to be able to inject the domain.

I'll go ahead and merge now, and then see if I can address that issue before I do a release.
